-- Schema Design Assignment

-- 4. Populate the Location table with the data provided below using INSERT statements (Remember all ids should be autogenerated):
--
-- city	state	country
-- Nashville	Tennessee	United States
-- Memphis	    Tennessee	United States
-- Phoenix	    Arizona	    United States
-- Denver	    Colorado	United States
INSERT INTO location (city, state, country) 
VALUES 
	('Nashville', 'Tennessee', 'United States'),
	('Memphis', 'Tennessee', 'United States'),
	('Phoenix', 'Arizona', 'United States'),
	('Denver', 'Colorado', 'United States');